### ISSUE TITLE
Problem when ngx-codemirror is hidden

### ISSUE THREAD

**Issue by cmglez10** [TypeCtrl/ngx-codemirror#12]
When you put the directive in a div witch can be hidden (eg. when data is loading from an API), paddings are not respected.

```
<div [hidden]="loading">
                      <ngx-codemirror
                        [(ngModel)]="module.template"
                        name="template"
                        [options]="{
                          lineNumbers: true,
                          theme: 'default',
                          mode: 'velocity'
                        }"
                      ></ngx-codemirror>
        </div>
```

**Comment by cmglez10** [comment]
As a workarround, if I change hidden directive by *ngIf, all works again

**Comment by scttcper** [comment]
you might also try display: none. but i think *ngIf is your best option.

**Comment by tiago-martinho** [comment]
When I do *ngIf in a div and put ngx-codemirror inside it it looses all styling and just shows a regular html textbox.

`  <div *ngIf="phase === 1">
    <ngx-codemirror
      [(ngModel)]="code"
      name="code"
      [options]="{
            lineNumbers: true,
            theme: 'default',
            mode: 'text/x-java'
            }"
    ></ngx-codemirror>
  </div>`

**Comment by sammaphey** [comment]
There are situations in which you do not want to use `*ngIf*` though but still want items to stay hidden. For example, if you are loading data in the background (underneath `*ngIf*` this will not allow data to load since it doesn't trigger angular) whilst `hidden` will allow angular to trigger. Perhaps that is poor design by myself or those who have implemented things in this way, but I think this is still a valid bug, since there will almost certainly be situations in which `hidden` is wrapped around `ngx-codemirror` and `*ngIf` won't fit everyones needs.
